package com.mogujie.tt.db.entity;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here

import com.mogujie.tt.imservice.entity.SearchElement;
import com.mogujie.tt.utils.pinyin.PinYin;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Id;
import org.greenrobot.greendao.annotation.Index;
import org.greenrobot.greendao.annotation.Keep;
import org.greenrobot.greendao.annotation.NotNull;
// KEEP INCLUDES END
import org.greenrobot.greendao.annotation.Transient;
import org.greenrobot.greendao.annotation.Generated;

/**
 * Entity mapped to table Department.
 */
@Entity(nameInDb = "DepartmentDao")
public class DepartmentEntity {
    @Id(autoincrement = true)
    private Long id;
    @NotNull
    @Index
    private int departId;
    /**
     * Not-null value.
     */
    @NotNull
    @Index
    private String departName;
    private int priority;
    private int status;
    private int created;
    private int updated;

    @Transient
    private PinYin.PinYinElement pinyinElement;
    @Transient
    private SearchElement searchElement;

    public DepartmentEntity() {
    }

    @Keep
    public DepartmentEntity(Long id) {
        this.id = id;
    }

    @Keep
    public DepartmentEntity(Long id, int departId, String departName, int priority, int status, int created, int updated) {
        this.id = id;
        this.departId = departId;
        this.departName = departName;
        this.priority = priority;
        this.status = status;
        this.created = created;
        this.updated = updated;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getDepartId() {
        return departId;
    }

    public void setDepartId(int departId) {
        this.departId = departId;
    }

    /**
     * Not-null value.
     */
    public String getDepartName() {
        return departName;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setDepartName(String departName) {
        this.departName = departName;
    }

    public int getPriority() {
        return priority;
    }

    public void setPriority(int priority) {
        this.priority = priority;
    }

    public int getStatus() {
        return status;
    }

    public void setStatus(int status) {
        this.status = status;
    }

    public int getCreated() {
        return created;
    }

    public void setCreated(int created) {
        this.created = created;
    }

    public int getUpdated() {
        return updated;
    }

    public void setUpdated(int updated) {
        this.updated = updated;
    }

    // KEEP METHODS - put your custom methods here

    public PinYin.PinYinElement getPinyinElement() {
        return pinyinElement;
    }

    public SearchElement getSearchElement() {
        return searchElement;
    }
    // KEEP METHODS END

}
