package com.mogujie.tt.db.entity;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here

import android.text.TextUtils;

import com.mogujie.tt.config.DBConstant;
import com.mogujie.tt.imservice.entity.SearchElement;
import com.mogujie.tt.utils.pinyin.PinYin;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Id;
import org.greenrobot.greendao.annotation.Keep;
import org.greenrobot.greendao.annotation.NotNull;
import org.greenrobot.greendao.annotation.Transient;
import org.greenrobot.greendao.annotation.Unique;

import java.io.Serializable;
import java.util.Collections;
import java.util.List;
import java.util.Set;
import java.util.TreeSet;
import org.greenrobot.greendao.annotation.Generated;

// KEEP INCLUDES END

/**
 * Entity mapped to table GroupInfo.
 */
@Entity(nameInDb = "GroupDao")
public class GroupEntity extends PeerEntity implements Serializable {
    private static final long serialVersionUID = -4393532900959974940L;
    @Id(autoincrement = true)
    protected Long id;
    @Unique
    @NotNull
    protected int peerId;
    //群名称
    @NotNull
    protected String mainName;
    //群头像
    @NotNull
    protected String avatar;
    @NotNull
    protected int created;
    @NotNull
    protected int updated;

    //群组类型，1-固定;2-临时群
    @NotNull
    private int groupType;
    //创建者用户id
    @NotNull
    private int creatorId;
    @NotNull
    private int userCnt;
    /**
     * Not-null value.
     */
    @NotNull
    private String userList;
    //群版本号
    @NotNull
    private int version;
    //是否删除,0-正常，1-删除
    @NotNull
    private int status;

    // KEEP FIELDS - put your custom fields here

    @Transient
    private PinYin.PinYinElement pinyinElement = new PinYin.PinYinElement();
    @Transient
    private SearchElement searchElement = new SearchElement();

    @Keep
    public GroupEntity() {
    }

    @Keep
    public GroupEntity(Long id) {
        this.id = id;
    }

    @Keep
    public GroupEntity(Long id, int peerId, int groupType, String mainName, String avatar, int creatorId, int userCnt, String userList, int version, int status, int created, int updated) {
        this.id = id;
        this.peerId = peerId;
        this.groupType = groupType;
        this.mainName = mainName;
        this.avatar = avatar;
        this.creatorId = creatorId;
        this.userCnt = userCnt;
        this.userList = userList;
        this.version = version;
        this.status = status;
        this.created = created;
        this.updated = updated;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getPeerId() {
        return peerId;
    }

    public void setPeerId(int peerId) {
        super.peerId = peerId;
        this.peerId = peerId;
    }

    public int getGroupType() {
        return groupType;
    }

    public void setGroupType(int groupType) {
        this.groupType = groupType;
    }

    /**
     * Not-null value.
     */
    public String getMainName() {
        return mainName;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setMainName(String mainName) {
        super.mainName = mainName;
        this.mainName = mainName;
    }

    /**
     * Not-null value.
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setAvatar(String avatar) {
        super.avatar = avatar;
        this.avatar = avatar;
    }

    public int getCreatorId() {
        return creatorId;
    }

    public void setCreatorId(int creatorId) {
        this.creatorId = creatorId;
    }

    public int getUserCnt() {
        return userCnt;
    }

    public void setUserCnt(int userCnt) {
        this.userCnt = userCnt;
    }

    /**
     * Not-null value.
     */
    public String getUserList() {
        return userList;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setUserList(String userList) {
        this.userList = userList;
    }

    public int getVersion() {
        return version;
    }

    public void setVersion(int version) {
        this.version = version;
    }

    public int getStatus() {
        return status;
    }

    public void setStatus(int status) {
        this.status = status;
    }

    public int getCreated() {
        return created;
    }

    public void setCreated(int created) {
        super.created = created;
        this.created = created;
    }

    public int getUpdated() {
        return updated;
    }

    public void setUpdated(int updated) {
        super.updated = updated;
        this.updated = updated;
    }

    // KEEP METHODS - put your custom methods here

    @Keep
    @Override
    public int getType() {
        return DBConstant.SESSION_TYPE_GROUP;
    }

    /**
     * yingmu
     * 获取群组成员的list
     * -- userList 前后去空格，按照逗号区分， 不检测空的成员(非法)
     */
    @Keep
    public Set<Integer> getlistGroupMemberIds() {
        if (TextUtils.isEmpty(userList)) {
            return Collections.emptySet();
        }
        String[] arrayUserIds = userList.trim().split(",");
        if (arrayUserIds.length <= 0) {
            return Collections.emptySet();
        }
        /**zhe'g*/
        Set<Integer> result = new TreeSet<Integer>();
        for (int index = 0; index < arrayUserIds.length; index++) {
            int userId = Integer.parseInt(arrayUserIds[index]);
            result.add(userId);
        }
        return result;
    }

    //todo 入参变为 set【自动去重】
    // 每次都要转换 性能不是太好，todo
    @Keep
    public void setlistGroupMemberIds(List<Integer> memberList) {
        String userList = TextUtils.join(",", memberList);
        setUserList(userList);
    }

    @Keep
    public PinYin.PinYinElement getPinyinElement() {
        return pinyinElement;
    }

    @Keep
    public void setPinyinElement(PinYin.PinYinElement pinyinElement) {
        this.pinyinElement = pinyinElement;
    }

    @Keep
    public SearchElement getSearchElement() {
        return searchElement;
    }

    @Keep
    public void setSearchElement(SearchElement searchElement) {
        this.searchElement = searchElement;
    }

    // KEEP METHODS END


    @Override
    public String toString() {
        return "GroupEntity{" +
        "id=" + id +
        ", peerId=" + peerId +
        ", mainName='" + mainName + '\'' +
        ", avatar='" + avatar + '\'' +
        ", created=" + created +
        ", updated=" + updated +
        ", groupType=" + groupType +
        ", creatorId=" + creatorId +
        ", userCnt=" + userCnt +
        ", userList='" + userList + '\'' +
        ", version=" + version +
        ", status=" + status +
        '}';
    }
}
